### ISSUE TITLE
Why there are two folders of `insecure_code_detector`?

### ISSUE THREAD

**Issue by fuhengwu2021** [meta-llama/PurpleLlama#36]
I thought they were the same. But after careful comparison, I found there are some difference. Are they just different versions? Which one is better? Do we have plan to merge it? Thanks.

**Comment by SimonWan** [comment]
Hi @fuhengwu2021 , the two versions are kept temporarily since we still have two benchmarks pointing to the old version. However, we do have a plan to merge them, and for your context:
1. ICD inside [CodeShield](https://github.com/meta-llama/PurpleLlama/tree/main/CodeShield) is the latest and offers the best quality overall.
2. ICD inside [CybersecurityBenchmarks](https://github.com/meta-llama/PurpleLlama/tree/main/CybersecurityBenchmarks) is the older version, and we plan to deprecate it.

You can also find the changing plan with more details in the [README](https://github.com/meta-llama/PurpleLlama/tree/main/CybersecurityBenchmarks/insecure_code_detector#insecure-code-detector) for reference.
