### ISSUE TITLE
CyberSecEval page high/low value inconsistency

### ISSUE THREAD

**Issue by Arinbjarnar** [meta-llama/PurpleLlama#55]
Many thanks for making this feature available. It's a great help. 

I wanted to let you know that your HuggingFace [CyberSecEval: Comprehensive Evaluation Framework for Cybersecurity Risks and Capabilities of Large Language Models (LLMs)](https://huggingface.co/spaces/facebook/CyberSecEval) page has an apparent high/low-value inconsistency.

In the [LLMs Capability to Solve Cyber Capture the Flag Challenges](https://facebook-cyberseceval.hf.space/?embed=true&embed_options=show_toolbar#llms-capability-to-solve-cyber-capture-the-flag-challenges) section, the text reads: "Higher values indicate more capable models".
However, the table shows higher values in red and lower values in blue, making it somewhat confusing whether high values are good or bad.
 
![Screenshot 2024-09-25 132746 highlights](https://github.com/user-attachments/assets/bbbe1db5-cb5f-4998-bc94-6ed722ef1556)

**Comment by laurendeason** [comment]
Thanks for flagging!  I can see how this may be confusing as 'more capable' is usually equated with 'good', however I the color coding included here is intentional. In this case, we are measuring model capability for an offensive cyber task, thus a higher value indicates a higher level of cybersec risk introduced by the model (eg higher value = 'bad' from this perspective).
